import type { FastifyInstance } from "fastify";
import type { Database } from "../db.js";
import { canReadGoals, canReadPerformance, performanceScopeSql, performanceScopeValues, resolveGoalAccess, resolvePerformanceAccess } from "./authorization.js";
import { loadFormalReport } from "./formal-reports.js";

function csvCell(value:unknown):string{if(value===null||value===undefined)return "";let text=String(value);if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`;}
function csv(rows:unknown[][]):string{return "\ufeff"+rows.map((row)=>row.map(csvCell).join(",")).join("\r\n");}
export async function registerExports(app:FastifyInstance,db:Database){
  app.get("/api/exports/formal-reports/:goalId.csv",async(request,reply)=>{if(!request.currentUser)return reply.code(401).send({message:"尚未登录"});const goalId=Number((request.params as {goalId?:string}).goalId);if(!Number.isSafeInteger(goalId)||goalId<=0)return reply.code(400).send({message:"目标标识无效"});const result=await loadFormalReport(db,request.currentUser,goalId);if(!result.ok)return reply.code(result.statusCode).send(result.body);const report=result.report;const rows:unknown[][]=[["正式业绩报表"],["目标月份","目标层级","责任人","生效目标","实际业绩","达成率"],[report.periodMonth,report.level,report.ownerName,report.targetAmount,report.actualAmount,report.achievementRate===null?"不计算":`${report.achievementRate}%`]];return reply.header("content-type","text/csv; charset=utf-8").header("content-disposition",`attachment; filename="sampleflow-formal-report-${report.periodMonth}-${report.goalId}.csv"`).send(csv(rows));});
  app.get("/api/exports/performance.csv",async(request,reply)=>{if(!request.currentUser)return reply.code(401).send({message:"尚未登录"});const access=await resolvePerformanceAccess(db,request.currentUser);if(!canReadPerformance(access))return reply.code(403).send({message:"当前角色没有业务导出权限"});const result=await db.query(`select o.qingflow_order_no,e.occurred_on::text,e.accounting_month::text,e.event_type,e.delta_amount::text,e.resulting_current_revenue::text,e.resulting_counted_amount::text,e.salesperson_name,e.department_name,e.group_name,e.reason from performance_events e join performance_orders o on o.id=e.order_id where ${performanceScopeSql("e",1)} order by e.occurred_on,e.id`,performanceScopeValues(access));const rows:unknown[][]=[["订单编号","发生日期","记账月份","事件类型","变动金额","当前营业额","计入业绩","业务员","部门","小组","原因"],...result.rows.map((row)=>Object.values(row))];return reply.header("content-type","text/csv; charset=utf-8").header("content-disposition",`attachment; filename="sampleflow-performance-${new Date().toISOString().slice(0,10)}.csv"`).send(csv(rows));});
  app.get("/api/exports/goals.csv",async(request,reply)=>{if(!request.currentUser)return reply.code(401).send({message:"尚未登录"});const access=await resolveGoalAccess(db,request.currentUser);if(!canReadGoals(access))return reply.code(403).send({message:"当前角色没有目标导出权限"});const result=await db.query(`select g.period_month::text,g.goal_level,u.username,u.display_name,v.version_no::text,v.amount::text,v.status,v.signature_text,v.signed_at::text,v.change_reason from goals g join users u on u.id=g.owner_user_id join goal_versions v on v.goal_id=g.id where ($1::boolean or g.owner_person_id=any($2::bigint[])) order by g.period_month,g.goal_level,u.display_name,v.version_no`,[access.all,access.ownerPersonIds]);const rows:unknown[][]=[["目标月份","目标层级","责任人账号","责任人姓名","版本","金额","状态","签名","签名时间","变更原因"],...result.rows.map((row)=>Object.values(row))];return reply.header("content-type","text/csv; charset=utf-8").header("content-disposition",`attachment; filename="sampleflow-goals-${new Date().toISOString().slice(0,10)}.csv"`).send(csv(rows));});
}
