import { type FormEvent, useEffect, useRef, useState } from "react";
import { ShieldCheck } from "lucide-react";
import { apiFetch, auditActionName, auditDataText, auditEntityName, readResponseJson } from "../app-api";
import type { AuditFilters, AuditRow } from "../app-types";
import { Pagination, parsePageNumber, parsePageSize, type PageSize } from "../shared-ui";

const emptyAuditFilters:AuditFilters={person:"",action:"",entityType:"",entityId:"",from:"",to:""};
const auditUrlKeys:Record<keyof AuditFilters,string>={person:"auditPerson",action:"auditAction",entityType:"auditEntityType",entityId:"auditEntityId",from:"auditFrom",to:"auditTo"};
function readAuditUrlState(){const params=new URLSearchParams(window.location.search);const filters={...emptyAuditFilters};for(const key of Object.keys(auditUrlKeys) as Array<keyof AuditFilters>)filters[key]=params.get(auditUrlKeys[key])??"";return{filters,page:parsePageNumber(params.get("auditPage")),pageSize:parsePageSize(params.get("auditPageSize"))};}
function writeAuditUrlState(filters:AuditFilters,page:number,pageSize:PageSize,mode:"push"|"replace"="push"){const params=new URLSearchParams(window.location.search);for(const key of Object.keys(auditUrlKeys) as Array<keyof AuditFilters>){if(filters[key])params.set(auditUrlKeys[key],filters[key]);else params.delete(auditUrlKeys[key]);}params.delete("auditCursor");params.set("auditPage",String(page));params.set("auditPageSize",String(pageSize));window.history[mode==="push"?"pushState":"replaceState"]({},"",`${window.location.pathname}?${params.toString()}${window.location.hash}`);}

function auditDateTime(value:string):string{return new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"medium",timeZone:"Asia/Shanghai"}).format(new Date(value));}
function auditTimeParameter(value:string):string{return value?`${value}${value.length===16?":00":""}+08:00`:"";}

export function AuditPage(){
  const initial=useRef(readAuditUrlState()).current;
  const[draft,setDraft]=useState<AuditFilters>(initial.filters);const[filters,setFilters]=useState<AuditFilters>(initial.filters);const[audits,setAudits]=useState<AuditRow[]>([]);const[page,setPage]=useState(initial.page);const[pageSize,setPageSize]=useState<PageSize>(initial.pageSize);const[totalCount,setTotalCount]=useState(0);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[revision,setRevision]=useState(0);
  useEffect(()=>{const restore=()=>{const state=readAuditUrlState();setDraft(state.filters);setFilters(state.filters);setPage(state.page);setPageSize(state.pageSize);setRevision((value)=>value+1);};window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore);},[]);
  const requestKey=JSON.stringify([filters,page,pageSize,revision]);
  useEffect(()=>{const controller=new AbortController();const params=new URLSearchParams({page:String(page),pageSize:String(pageSize)});for(const key of ["person","action","entityType","entityId"] as const)if(filters[key])params.set(key,filters[key]);if(filters.from)params.set("from",auditTimeParameter(filters.from));if(filters.to)params.set("to",auditTimeParameter(filters.to));setLoading(true);setError("");apiFetch(`/api/audits?${params}`,{signal:controller.signal}).then(async(response)=>{const data=await readResponseJson<{audits?:AuditRow[];page?:number;pageSize?:PageSize;totalCount?:number;message?:string}>(response,"审计响应无效，请重试。");if(!response.ok)throw new Error(data.message??"审计查询失败");const total=data.totalCount??0;const lastPage=Math.max(1,Math.ceil(total/pageSize));if(page>lastPage){writeAuditUrlState(filters,lastPage,pageSize,"replace");setPage(lastPage);return;}setAudits(data.audits??[]);setTotalCount(total);}).catch((reason)=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"审计查询失败");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[requestKey]);
  function update(key:keyof AuditFilters,value:string){setDraft((current)=>({...current,[key]:value}));}
  function query(event:FormEvent){event.preventDefault();const next=Object.fromEntries(Object.entries(draft).map(([key,value])=>[key,value.trim()])) as AuditFilters;writeAuditUrlState(next,1,pageSize);setFilters(next);setPage(1);setRevision((value)=>value+1);}
  function clear(){writeAuditUrlState(emptyAuditFilters,1,pageSize);setDraft(emptyAuditFilters);setFilters(emptyAuditFilters);setPage(1);setRevision((value)=>value+1);}
  function changePage(nextPage:number){writeAuditUrlState(filters,nextPage,pageSize);setPage(nextPage);}
  function changePageSize(nextPageSize:PageSize){writeAuditUrlState(filters,1,nextPageSize);setPageSize(nextPageSize);setPage(1);}
  return <main className="dashboard"><header><div><h1>审计查询</h1><p>按账号、动作、实体和时间追溯不可变记录；数据范围沿用当前角色权限</p></div></header><div className="permission-note"><ShieldCheck size={18}/>此页面只提供查询，不提供修改或删除入口；敏感凭据字段不会返回。</div><section className="orders-card" aria-labelledby="audit-table-title"><div className="orders-toolbar"><div><h2 id="audit-table-title">审计记录</h2><span role="status">{loading?"正在查询…":error?"查询失败":`本页 ${audits.length} 条记录`}</span></div></div><form noValidate className="order-filters" onSubmit={query}><div className="order-filter-grid"><label className="field"><span>人员</span><input value={draft.person} onChange={(event)=>update("person",event.target.value)} placeholder="姓名、账号或人员标识"/></label><label className="field"><span>动作</span><input value={draft.action} onChange={(event)=>update("action",event.target.value)} placeholder="如订单入账、账号变更"/></label><label className="field"><span>实体类型</span><input value={draft.entityType} onChange={(event)=>update("entityType",event.target.value)} placeholder="如订单、账号、组织"/></label><label className="field"><span>实体标识</span><input value={draft.entityId} onChange={(event)=>update("entityId",event.target.value)} placeholder="稳定标识"/></label><label className="field"><span>开始时间</span><input type="datetime-local" value={draft.from} onChange={(event)=>update("from",event.target.value)}/></label><label className="field"><span>结束时间</span><input type="datetime-local" value={draft.to} onChange={(event)=>update("to",event.target.value)}/></label></div><div className="order-filter-actions"><button type="button" onClick={clear}>清除条件</button><button type="submit">查询审计</button></div></form>{error?<div className="query-feedback"><p className="page-message" role="alert">{error}</p><button type="button" onClick={()=>setRevision((value)=>value+1)}>重试查询</button></div>:null}<div className="orders-table-wrap" tabIndex={0} role="region" aria-label="审计记录，可横向滚动"><table className="audit-table"><thead><tr><th>时间</th><th>人员</th><th>动作</th><th>实体</th><th>变更前</th><th>变更后</th></tr></thead><tbody>{!loading&&!error&&audits.length===0?<tr><td className="empty-cell" colSpan={6}>没有符合当前权限和条件的审计记录。</td></tr>:audits.map((row)=><tr key={row.id}><td><time dateTime={row.createdAt}>{auditDateTime(row.createdAt)}</time></td><td>{row.actorDisplayName??"系统"}<small className="table-secondary">{row.actorUsername??row.actorPersonId??"—"}</small></td><td>{auditActionName(row.action)}</td><td>{auditEntityName(row.entityType)}<small className="table-secondary">{row.entityId??"—"}</small></td><td className="audit-data">{auditDataText(row.beforeData)}</td><td className="audit-data">{auditDataText(row.afterData)}</td></tr>)}</tbody></table></div><Pagination label="审计记录" page={page} pageSize={pageSize} totalItems={totalCount} disabled={loading||!!error} onPageChange={changePage} onPageSizeChange={changePageSize}/></section></main>;
}
